html: prosperon.org
	emacs prosperon.org -f org-html-export-to-html --kill
	mv prosperon.html index.html
	mkdir html
	cp index.html orb.gif dos.ttf org-info.js style.css prosperon_orb_horizontal.gif html
